version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python app.py
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
